In [ ]:
a = [1,2,3,4]

a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]

a[0][1]

In [2]:
import numpy as np

In [5]:
a = [1,2,3,4]
print(a, type(a))

[1, 2, 3, 4] <class 'list'>


In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [7]:
zerosarr = np.zeros((3,3))
print(zerosarr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
zerosarr = np.ones((3,3))
print(zerosarr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
rand_arr = np.random.rand(5, 5) 
print(rand_arr)

[[0.46381747 0.88050493 0.70040944 0.46778649 0.8327479 ]
 [0.11912402 0.61998793 0.29564553 0.50645727 0.76616188]
 [0.87711603 0.05044106 0.61781001 0.18925493 0.18806888]
 [0.99915455 0.02489039 0.01549533 0.49311112 0.83795028]
 [0.80004202 0.3434729  0.51594874 0.61472797 0.48065505]]


In [24]:
a = [[[1,2,3],
    [4,5,6],
    [7,8,9]],
    ]

a[1][1][0]

IndexError: list index out of range

In [14]:
arr = np.array([1,2,3,4])
print(arr)
print(arr.shape)

[1 2 3 4]
(4,)


In [30]:
# [1,2,3,4]
a = [[1,2,3],[4,5,6],[7,8,9]]
print(a[0])
print(a[1])
print(a[2])
a[1][0]

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


4

In [42]:
arr = np.array([1,2,3,4,5,6], ndmin=2)
print(arr)
# print
print(arr.shape)
# print(arr[0])
# print(arr[0][0])



[[1 2 3 4 5 6]]
(1, 6)


In [47]:
print(arr.reshape((3,2)))  
print(type(arr))  
print(arr.shape)  
print(arr.ndim)  

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
(1, 6)
2


In [56]:
arr = np.array([1,2,3,4, 'str'])  
print(arr, type(arr[0]))

['1' '2' '3' '4' 'str'] <class 'numpy.str_'>


In [60]:
a = [1,2,3,4,5,6,7]
a[:]

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
element = arr[0, 1]  # Accessing the element at the first row and second column
# slice_ro# Slicing
w = arr[1, :]  # Slicing the second row
# slice_column = arr[:, 2]  

In [61]:
arr = np.array([1,2,3,4,5,6], ndmin=2)
reahape = arr.reshape(2,3)
print(reahape)

[[1 2 3]
 [4 5 6]]


In [70]:
slice = reahape[1:,2]
print(slice)

[6]


In [75]:
arr = np.array([1,2,3,4,5,6,7,8,9,10], ndmin=2)
out = arr > 8
out2 = arr[out]
print(out)
print(out2)

[[False False False False False False False False  True  True]]
[ 9 10]


In [ ]:
arr[arr>150] = 255
arr[arr<150] = 0

In [76]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [78]:
print(b)
b[0,0] = 77
print(b)

[[2 3]
 [6 7]]
[[77  3]
 [ 6  7]]


In [ ]:
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   

In [80]:
a = [1,2,3]
b= [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [79]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
addition = arr1 + arr2
print(addition)

[5 7 9]


In [ ]:


1,2,3,4,5,6,7,8

In [87]:
arr1 = np.array([2,7,4,3,5,6,7,8])

print(np.mean(arr1))
print(np.median(arr1))
np.std(arr1)

sqrt = np.sqrt(arr1)

print(sqrt)

5.25
5.5
[1.41421356 2.64575131 2.         1.73205081 2.23606798 2.44948974
 2.64575131 2.82842712]


In [2]:
import pandas as pd

In [89]:
data = [10, 20, 30, 40, 50]
series_from_list = pd.Series(data)
print(series_from_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [92]:
custom_index = pd.Series(data, index=['A', 'B', 'C', 'D', 'E'])
print(custom_index)

A    10
B    20
C    30
D    40
E    50
dtype: int64


In [93]:
element_at_position_2 = series_from_list[2]
print(element_at_position_2)

element_with_label_B = custom_index['B']
print(element_with_label_B)
slice_series = series_from_list[1:4] # Returns elements at positions 1, 2, and 3
print(slice_series)

30
20
1    20
2    30
3    40
dtype: int64


In [5]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],
     'Age': [25, 30, 35]}
df_from_dict = pd.DataFrame(data)
# print(df_from_dict)

name_column = df_from_dict['Age']
print(name_column)

young_people = df_from_dict[df_from_dict['Age'] < 30]
print(young_people)

cell_value = df_from_dict.at[2, 'Name']
print(cell_value)

0    25
1    30
2    35
Name: Age, dtype: int64
    Name  Age
0  Alice   25
Charlie


In [ ]:
pd.read_csv('data.xlsx')

In [9]:
data_list = [['Alice', 25,56, 90], ['Bob', 30], ['Charlie', 35]]
df_from_list = pd.DataFrame(data_list, columns=['asdes', 'Age', "sdfds", 'sdfds'])
print(df_from_list)

     asdes  Age  sdfds  sdfds
0    Alice   25   56.0   90.0
1      Bob   30    NaN    NaN
2  Charlie   35    NaN    NaN


In [20]:
df_from_csv = pd.read_csv('C:/Users/X3/Downloads/BIA Lecture Material/numpy/data.csv')
print(df_from_csv.tail(5))

    Index      Customer Id First Name Last Name                Company  \
95     96  cb8E23e48d22Eae       Karl     Greer              Carey LLC   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson  Ware, Burns and Oneal   
97     98  28CDbC0dFe4b1Db       Fred    Guerra          Schmitt-Jones   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer     Fitzgerald-Harrell   
99    100  2354a0E336A91A1   Clarence    Haynes     Le, Nash and Cross   

               City          Country               Phone 1  \
95     East Richard           Guyana   (188)169-1674x58692   
96     New Bradview        Sri Lanka       +1-846-706-2218   
97       Ortegaland  Solomon Islands  +1-753-067-8419x7170   
98  Lake Elijahview            Aruba         (530)311-9786   
99        Judymouth         Honduras         (753)813-6941   

                   Phone 2                           Email Subscription Date  \
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30   
96            605.413.

In [26]:
data_from_json = pd.read_json('C:/Users/X3/Downloads/BIA Lecture Material/numpy/data.json')
print(data_from_json)

                 name language                id  \
0       Adeel Solangi   Sindhi  V59OF92YF627HFY0   
1       Afzal Ghaffar   Sindhi  ENTOCR13RSCLZ6KU   
2       Aamir Solangi   Sindhi  IAKPO3R4761JDRVG   
3       Abla Dilmurat   Uyghur  5ZVOEPMJUI4MB4EN   
4            Adil Eli   Uyghur  6VTI8X6LL0MMPJCC   
...               ...      ...               ...   
15835   Bhupesh Menon    Hindi  0CEPNRDV98KT3ORP   
15836    Rohini Vasav    Hindi  UEFML43TCGS04KWM   
15837    Sunil Kapoor    Hindi  VY2A0APGVHK5NAW2   
15838  Zamokuhle Zulu  isiZulu  XU7BX2F8M5PVZ1EF   
15839   Bhupesh Menon    Hindi  0CEPNRDV98KT3ORP   

                                                     bio  version  
0      Donec lobortis eleifend condimentum. Cras dict...     6.10  
1      Aliquam sollicitudin ante ligula, eget malesua...     1.88  
2      Vestibulum pharetra libero et velit gravida eu...     7.27  
3      Donec lobortis eleifend condimentum. Morbi ac ...     2.53  
4      Vivamus id faucibus velit, i

In [ ]:
class Task:
    def func1(set1,set2):
        pass
        # all work here
        # xyz = set1.interf()set2
        # return xyz 
        return
    
    def func2():
        pass
        return
    
    def func3():
        pass
        return
    
t1 = Task()
paramter = "sfsdf"
out = t1.func1(set1,set2)
print(out)

In [27]:
"""Sample example to review

Grocery Store Inventory System
Create a simple inventory system for a grocery store.

Requirements:

Create a GroceryStore class to manage items in the store. It should:
Add items to the inventory having name, quantity and price per item.
Show available items and their details.
Calculate the total value of the inventory.

"""
class GroceryStore:
    def __init__(self):
        self.inventory = {}

    def add_item(self, name, quantity, price_per_item):
        self.inventory[name] = (quantity, price_per_item)

    def display_inventory(self):
        for item, details in self.inventory.items():
            print(f"Item: {item}, Quantity: {details[0]}, Price per item: {details[1]}")

    def total_inventory_value(self):
        total_value = sum(quantity * price for quantity, price in self.inventory.values())
        return total_value

# Example Usage
store = GroceryStore()
store.add_item("Apple", 50, 1)
store.add_item("Banana", 100, 0.5)
store.display_inventory()
total_value = store.total_inventory_value()
print(f"Total Inventory Value: {total_value}")



Item: Apple, Quantity: 50, Price per item: 1
Item: Banana, Quantity: 100, Price per item: 0.5
Total Inventory Value: 100.0


In [ ]:
"""

Task need to be completed

** note -  make all function with suitable variablename, functionname, classname in structure format with proper indentation

Task 10 :- 

Movie Collection Tracker
Create a program that tracks your personal movie collection.

Requirements:

Create a MovieCollection class that:
Adds movies to the list.
Displays all movies.
Searches for a movie by title if movie is in list then print movie found if not found then movie not found.




"""